cd /sysdev/s9/bruno/acoel_phylo/data

catalog insert --id "NwesRNAseq" --paths "/sysdev/s9/bruno/Nemertoderma_westbladi/RNAseq/data/C3G0PACXX_NemertodermaRNA_13s007066-1-1_Hejnol_lane313s007066_1_sequence.txt.gz:/sysdev/s9/bruno/Nemertoderma_westbladi/RNAseq/data/C3G0PACXX_NemertodermaRNA_13s007066-1-1_Hejnol_lane313s007066_2_sequence.txt.gz" --species "Nemertoderma westbladi" --ncbi_id "172109" --itis_id "53970" --sequencer "Illumina HiSeq 2000" --seq_center "GeneCore"
catalog insert --id "DgyrRNAseq" --paths "/sysdev/s9/bruno/Dinophilus_gyrociliatus/RNAseq/data/C39NFACXX_DinophilusRNAseq_13s005120-1-1_Hejnol_lane113s005120_1_sequence.txt.gz:/sysdev/s9/bruno/Dinophilus_gyrociliatus/RNAseq/data/C39NFACXX_DinophilusRNAseq_13s005120-1-1_Hejnol_lane113s005120_2_sequence.txt.gz" --species "Dinophilus gyrociliatus" --ncbi_id "120995" --itis_id "68408" --sequencer "Illumina HiSeq 2000" --seq_center "GeneCore"
catalog insert --id "PcauRNAseq" --paths "/sysdev/s9/bruno/Priapulus_caudatus/RNAseq/agalma/data/C2ARHACXX_PcauRNAseq_13s004116-1-1_Hejnol_lane113s004116_1_sequence.txt.gz:/sysdev/s9/bruno/Priapulus_caudatus/RNAseq/agalma/data/C2ARHACXX_PcauRNAseq_13s004116-1-1_Hejnol_lane113s004116_2_sequence.txt.gz" --species "Priapulus caudatus" --ncbi_id "37621" --itis_id "155156" --library_id "transcriptome" --sequencer "Illumina" --seq_center "GENECORE - EMBL Genomic Core Facilities"
catalog insert --id "SRX365617" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1014618_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1014618_2.fastq.gz" --species "Evechinus chloroticus" --ncbi_id "137513" --library_id "SRR1014618" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "University of Otago" --note "Combined sample of RNA extracted from adult male Evechinus chloroticus roe, muscle, gut, water vascular system and coelomic fluid"
catalog insert --id "SRX366292" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1014619_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1014619_2.fastq.gz" --species "Evechinus chloroticus" --ncbi_id "137513" --library_id "SRR1014619" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "University of Otago" --note "Combined sample of RNA extracted from adult female Evechinus chloroticus roe, muscle, gut, water vascular system and coelomic fluid"
catalog insert --id "SRX113900" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR396667_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR396667_2.fastq.gz" --species "Taenia multiceps" --ncbi_id "94034" --library_id "SRR396667" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "Sichuan Agriculture University" --note "Adult stage of Taenia multiceps from the dog intestine."
catalog insert --id "SRX130438" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR446605_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR446605_2.fastq.gz" --species "Loa loa" --ncbi_id "7209" --library_id "SRR446605" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer II" --seq_center "BI" --sample_prep "Perform RNA sequencing on Loa Loa to assist in genome annotation."
catalog insert --id "SRX110652" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR388222_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR388222_2.fastq.gz" --species "Penaeus monodon" --ncbi_id "6687" --library_id "SRR388222" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer II" --seq_center "Nofima"
catalog insert --id "ERX200391" --paths "/sysdev/s9/bruno/acoel_phylo/data/ERR225731_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/ERR225731_2.fastq.gz" --species "Onchocerca volvulus" --ncbi_id "6282" --library_id "ERR225731" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "SC" --sample_prep "Illumina sequencing of library 3731336, constructed from sample accession ERS092577 for study accession ERP001350.  This is part of an Illumina multiplexed sequencing run (6970_8).  This submission includes reads tagged with the sequence ATCACGTT."
catalog insert --id "SRX118365" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR404226_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR404226_2.fastq.gz" --species "Crassostrea virginica" --ncbi_id "6565" --library_id "SRR404226" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "Institue of oceanology, Chinese academic of scienc" --note "The sample was from cultural family and approximately 60 mm in shell height. According the polymorphism, only one individual per was selected for RNA extraction. Before sampled, the oyster was acclimatized in seawater tanks at a temperature of 20 *C and a salinity of 30."
catalog insert --id "SRX251927" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR786599_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR786599_2.fastq.gz" --species "Hormogaster elisae" --ncbi_id "452200" --library_id "SRR786599" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "Harvard University" --note "Tissues that are not reproductive or digestive" --sample_prep "RNA from mixed tissues of the animal. Library construction following protocol in Novo et al 2013. Pheromone evolution, reproductive genes, and comparative transcriptomics in Mediterranean earthworms (Annelida, Oligochaeta, Hormogastridae). Molecular Biology and Evolution.   True seq library preparation kit and sequencing in Illumina Hi-seq 2000"
catalog insert --id "SRX122622" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR414930_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR414930_2.fastq.gz" --species "Apostichopus japonicus" --ncbi_id "307972" --library_id "SRR414930" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "liaoning ocean and fisheries science research inst" --note "Pooled sample of Apostichopus japonicus tissues and samples from every development stages. Tissues include body wall, intestine, respiratory trees, coelomocytes, male and female gonad, Samples from every development stages include unfertilized eggs, fertilized eggs, cellulous stages, blastula prior to hatching, gastrula, early auricularia, auricularia, late auricularia, doliolaria, pentactula and 1-mm long juvenile."
catalog insert --id "SRX288430" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR871527_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR871527_2.fastq.gz" --species "Nanomia bijuga" --ncbi_id "168759" --library_id "SRR871527" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "Dunnlab" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
catalog insert --id "SRR1014618-SRR1014619" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1014618-SRR1014619_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1014618-SRR1014619_2.fastq.gz" --species "Evechinus chloroticus" --ncbi_id "137513" --library_id "SRR1014619" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "University of Otago" --note "Combined sample of RNA extracted from adult male and female Evechinus chloroticus roe, muscle, gut, water vascular system and coelomic fluid | Merged FASTQ files."
catalog insert --id "SRX147910" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR496794_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR496794_2.fastq.gz" --species "Fascioloides magna" --ncbi_id "394415" --library_id "SRR496794" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer IIx" --seq_center "The University of Melbourne" --note "Total RNA was extracted from three individual adults of F. magna using the TriPure reagent (Roche) and DNase I-treated"
catalog insert --id "SRX057839" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR189060_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR189060_2.fastq.gz" --species "Clonorchis sinensis" --ncbi_id "79923" --library_id "SRR189060" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer IIx" --seq_center "Sun Yat-sen University" --note "we conducted transcriptome sequencing of a Clonorchis sinensis adult from Guangdong province in China."
catalog insert --id "SRX333585" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR950367_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR950367_2.fastq.gz" --species "Dermacentor reticulatus" --ncbi_id "57047" --library_id "SRR950367" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer IIx" --seq_center "Era7 Bioinformatics"
catalog insert --id "SRX360523" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1048659_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1048659_2.fastq.gz" --species "Gasteracantha hasselti" --ncbi_id "1401002" --library_id "SRR1048659" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2500" --seq_center "Kunming Institute of Zoology, Chinese Academy of S" --note "Transcriptome sequencing clean data of Gasteracantha hasselti "
catalog insert --id "SRX360519" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1048826_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1048826_2.fastq.gz" --species "Macracantha arcuata" --ncbi_id "1401004" --library_id "SRR1048826" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2500" --seq_center "Kunming Institute of Zoology, Chinese Academy of S" --note "Transcriptome sequencing clean data of Gasteracantha arcuata "
catalog insert --id "SRX360521" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR1048661_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR1048661_2.fastq.gz" --species "Nasoonaria sinensis" --ncbi_id "1401006" --library_id "SRR1048661" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2500" --seq_center "Kunming Institute of Zoology, Chinese Academy of S" --note "Transcriptome sequencing clean data of Nasoonaria sinensis "
catalog insert --id "SRX205297" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR618563_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR618563_2.fastq.gz" --species "Metasiro americanus" --ncbi_id "397056" --library_id "SRR618563" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina Genome Analyzer II" --seq_center "Harvard University"
catalog insert --id "ERX311347" --paths "/sysdev/s9/bruno/acoel_phylo/data/ERR338470_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/ERR338470_2.fastq.gz" --species "Eupolybothrus sp. PS-2013" --ncbi_id "1391732" --library_id "ERR338470" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "GigaScience" --note "Protocols: Manual collection of specimen from natural habitat (cave), crushed and preserved in liquid RNA-later (Qiagen, USA). Total RNA was extract using TRIzol reagent (Invitrogen, USA) according to the manufacturer's instructions. Messenger RNA (mRNA) was isolated from total RNA using the Dynabeads mRNA Purification Kit (Invitrogen, Carlsbad Ca.USA). The mRNA was fragmented and transcribed into first-strand cDNA using SuperScript(tm) II Reverse Transcriptase (Invitrogen, Carlsbad Ca. USA) and N6 primer (IDT). RNase H (Invitrogen, Carlsbad Ca. USA) and DNA polymerase I (Invitrogen, Shanghai ChinaNew England BioLabs) were subsequently applied to synthesize the second-strand cDNA. The double-stranded cDNA then underwent end-repair, a single 'A' base addition, adapter ligation, and size selection (~250bp), indexed and PCR amplification to construct library." --sample_prep "Transcriptome analysis of the newly described centipede Eupolybothrus cavernicolus sp.n."
catalog insert --id "SRX120026" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR426837_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR426837_2.fastq.gz" --species "Tetraclita japonica" --ncbi_id "240496" --library_id "SRR426837" --library_type "TRANSCRIPTOMIC" --sequencer "Illumina HiSeq 2000" --seq_center "Biodiversity Research Center, Academia Sinica" --note "One individual was collected from the rocky shore of Shen-Ao Keng, Keelung, Taiwan (25*7'25.24"N, 121*49'11.26"E) in March 2011."

# phred64, needs conversion.
#SRX425456

# rRNAs absent, breaks pipeline.
#SRX096026
#SRX096027
#catalog insert --id "SRX096026" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR341938_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR341938_2.fastq.gz" --species "Bursaphelenchus xylophilus" --ncbi_id "6326" --library_id "SRR341938" --library_type "OTHER" --sequencer "Illumina Genome Analyzer II" --seq_center "Individual" --note "source: Mixed stages"
#catalog insert --id "SRX096027" --paths "/sysdev/s9/bruno/acoel_phylo/data/SRR341939_1.fastq.gz:/sysdev/s9/bruno/acoel_phylo/data/SRR341939_2.fastq.gz" --species "Bursaphelenchus mucronatus" --ncbi_id "6325" --library_id "SRR341939" --library_type "OTHER" --sequencer "Illumina Genome Analyzer II" --seq_center "Individual" --note "source: Mixed stages"

# Note from SRX110652 which does not work with catalog export.
#Two individuals from Chennai; two from Tuticorin; and three from Vishakhapatnam. Shrimp were dissected under sterile conditions and fresh tissue samples (hepatopancreas, muscle, nervous tissue, intestinal tract, heart, gonad, gill, pleopod and lymphoid organ) were collected and stored in 1.5 ml microtubes. Microtubes were filled with RNAlater (Qiagen) to immerse the entire tissue. Subsequently, tubes were topped up to the brim with RNAlater, capped and stored at room temperature for two hours, 4 oC overnight and -80 oC until further use. RNA was extracted (TRIzol Plus RNA Purification, Invitrogen) according to manufacturer’s instructions. Tissue was ground in liquid nitrogen and 1.5 ml of TRIzol was added. RNA was further purified by chloroform extraction followed by precipitation using isopropanol and one wash with 70% ethanol. RNA was resuspended in 25 µl of RNase-free water. Only samples with optimal purity (OD260/280 &gt;1.8 and &lt;2.2; OD260/230&gt;1.0 and &lt;2.4) and concentration (&gt;50 ng/µl and &lt;2500 ng/µl), estimated using UV spectrophotometry (Nanodrop) and capillary electrophoresis (Agilent Bioanalyser), were utilized for sequencing. Samples were prepared using the Illumina protocol outlined in Preparing Samples for Sequencing of mRNA (Part# 1004898 Rev. A September 2008).
